### ISSUE TITLE
The future of Herd 

### ISSUE THREAD

**Issue by ghost** [imjacobclark/Herd#2]
I wondered if you planned to take this tool any further? I'd probably not use YAML to write tests as it becomes a little tricky when writing non-trivial tests. [Gatling](http://gatling.io/) uses a DSL, but I'd probably stick to standard  Rust.

**Comment by imjacobclark** [comment]
Hi @aidylewis, I'm a colleague of yours at the BBC, working as a developer in K&L, I believe we've spoke before. 

I do plan to do further development of this, it's just getting the time to pick this up.

I plan at some point to get the following up and running:
- Ramp up scenario
- Batched scenario
- Accept command line flags to begin a test
- Export data to influxDB or other data store
- Graph metrics
- Master/Slave mode to orchestrate a thundering herd via a message broker

**Comment by ghost** [comment]
Fantastic. I think this is a real promising project. If you give me a couple of weeks to learn the Rust essentials I'll help you. I'll take your guidance on what you would like me to  implement. Can I ask you why you used the MIT license and not the GPL? The MIT license allows the use in proprietary software.

**Comment by imjacobclark** [comment]
@aidylewis I didn't put too much thought into the licence when I started the project and just threw an MIT on there!

I'm generally on IRC in #knowlearn via the BBC server if you wanna catch up away from GitHub!
